/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.number.baseball;

import edu.number.baseball.game.NumberBaseBallGame;

public class App {
    public static void main(String[] args) {
        NumberBaseBallGame game = new NumberBaseBallGame();
        game.run();
    }
}
